#!/bin/sh
echo -n "\033[1;33m"
echo "   __ __ __ ______  ____  ____"
echo "  / / ／/ // / __ \/ __ \/ __/"
echo " / / \_/ // / /_/ / /_/ /\ \  "
echo "/_/ \_/\___/_____/\____/___/  "
echo -n "\033[0;39m"

printf "\n"
printf " * GitHub:         https://github.com/9udos\n"
